### PR TITLE
Base URL for Development

### LINKED ISSUE #26: Setup .env to allow setting up different backend address for local development
This is needed as for local development need to update the connection URL in request.js
baseURL: httpo://localhost:8881/api/',

and in production it should be
baseURL: '/api/',

### PR DESCRIPTION
**Pull request by bsuligoj**
Different Base URL based on mode.

closes https://github.com/SmartParksOrg/smartparks-connect-web/issues/26

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
could you also add an example env file and mention how to use it in the readme for local env

maybe something like
.env_example

and to use it for local development can just rename it to .env

also add .env to .gitignore so that it doesn't end up in the repo and get deployed to the prod server

**Comment by bsuligoj** [comment]
You don't need .env specified. If you build vue project for production (npm run build) the mode will be **production**. If you run the npm development server (npm run dev) the mode will be **development**

**Comment by krasi-georgiev** [comment]
nice, this is even easier.

Can you update the readme with the new instructions how to run the backend and the frontend?

**Comment by bsuligoj** [comment]
Updated.

**Pull request merged**
